### ISSUE TITLE
Use of non-standard relation.

### ISSUE THREAD

**Issue by jevolk** [maubot/echo#3]
The use of relation `rel_type` of `pong` Introduced by e9b4cd47a2b29c0af071188ef08bedc0dd0d717f and manifests substantial [bugs](https://github.com/element-hq/element-web/issues/27132) is [non-standard and not approved for use](https://github.com/element-hq/element-web/issues/27132#issuecomment-1981064923).

>  It is entirely to do with them using a non-standard relation.

Possible considerations for abatement:
- Apply for standard approval of the relation.
- Replace with a pre-approved relation.

**Comment by tulir** [comment]
The exact relation type isn't relevant, it's just a bug in element's thread handling that happens with any relation type, including standard ones like `m.reference`. The `rel_type` was also already changed to `xyz.maubot.pong` in https://github.com/maubot/echo/commit/4ade10737037bf5cc063b1d2ca749d3c78a58c80 to follow the spec on custom types
